"""initial_schema

Revision ID: 09d44398ee6a
Revises: 
Create Date: 2026-03-13 18:39:23.724331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d44398ee6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_message_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('should_respond', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=True),
    sa.Column('sent_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_decisions_id'), 'bot_decisions', ['id'], unique=False)
    op.create_table('guild_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('proactive_mode', sa.Boolean(), nullable=True),
    sa.Column('global_cooldown', sa.Integer(), nullable=True),
    sa.Column('persona', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_settings_guild_id'), 'guild_settings', ['guild_id'], unique=True)
    op.create_index(op.f('ix_guild_settings_id'), 'guild_settings', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('cleaned_content', sa.Text(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_messages_guild_id'), 'messages', ['guild_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('channel_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_settings.guild_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_settings_channel_id'), 'channel_settings', ['channel_id'], unique=True)
    op.create_index(op.f('ix_channel_settings_guild_id'), 'channel_settings', ['guild_id'], unique=False)
    op.create_index(op.f('ix_channel_settings_id'), 'channel_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_settings_id'), table_name='channel_settings')
    op.drop_index(op.f('ix_channel_settings_guild_id'), table_name='channel_settings')
    op.drop_index(op.f('ix_channel_settings_channel_id'), table_name='channel_settings')
    op.drop_table('channel_settings')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_guild_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_guild_settings_id'), table_name='guild_settings')
    op.drop_index(op.f('ix_guild_settings_guild_id'), table_name='guild_settings')
    op.drop_table('guild_settings')
    op.drop_index(op.f('ix_bot_decisions_id'), table_name='bot_decisions')
    op.drop_table('bot_decisions')
    # ### end Alembic commands ###
